
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - servicemonitor.yml
  - networkpolicy.yml
  - poddisruptionbudget.yml

labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
