
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - rollout.yml
  - service-canary.yml
  - analysis-template.yml

replicas:
  - name: sample-app
    count: 1

images:
  - name: ghcr.io/bamideleflint/argostack/sample-app
    newTag: main-c7cedc1

patchesStrategicMerge:
  - patch-delete-deployment.yml
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "64Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "128Mi"
    target:
      kind: Rollout
      name: sample-app
