
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

patchesStrategicMerge:
  - patch-delete-deployment.yml
resources:
  - ../../base
  - rollout.yml

replicas:
  - name: sample-app
    count: 3

images:
  - name: ghcr.io/bamideleflint/argostack/sample-app
    newTag: v1.0.0

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
    target:
      kind: Deployment
      name: sample-app
